services:

  postgres:
    image: pgvector/pgvector:pg16

    container_name: fake-news-postgres

    restart: always

    environment:
      POSTGRES_DB: fake_news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "4588:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - fake-news-network


  pgadmin:

    image: dpage/pgadmin4

    container_name: fake-news-pgadmin

    restart: always

    environment:

      PGADMIN_DEFAULT_EMAIL:
        admin@fakenews.com

      PGADMIN_DEFAULT_PASSWORD:
        admin


    ports:

      - "5050:80"


    depends_on:

      - postgres


    networks:

      - fake-news-network



networks:

  fake-news-network:

    driver: bridge



volumes:

  postgres_data: