"""add provider model dimensions to embeddings

Revision ID: 73a75c3a1744
Revises: b0ba8c50fdea
Create Date: 2026-07-27 11:29:11.836586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73a75c3a1744'
down_revision: Union[str, Sequence[str], None] = 'b0ba8c50fdea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('embeddings', sa.Column('model', sa.String(length=120), nullable=False))
    op.add_column('embeddings', sa.Column('dimensions', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('embeddings', 'dimensions')
    op.drop_column('embeddings', 'model')
    op.drop_column('embeddings', 'provider')
    # ### end Alembic commands ###
