"""update embedding dimension to 3072

Revision ID: b0ba8c50fdea
Revises: e9a31377ffac
Create Date: 2026-07-27 06:13:42.056885

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = "b0ba8c50fdea"
down_revision: Union[str, Sequence[str], None] = "e9a31377ffac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("embeddings", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=Vector(1536),
        type_=Vector(3072),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "embeddings",
        "vector",
        existing_type=Vector(3072),
        type_=Vector(1536),
        existing_nullable=False,
    )
    op.drop_column("embeddings", "created_at")
    # ### end Alembic commands ###
