"""create news table

Revision ID: e9a31377ffac
Revises: c051bb01e0e5
Create Date: 2026-07-27 04:21:05.422477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a31377ffac'
down_revision: Union[str, Sequence[str], None] = 'c051bb01e0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('author', sa.String(length=255), nullable=True))
    op.add_column('news', sa.Column('url', sa.String(length=1000), nullable=True))
    op.add_column('news', sa.Column('language', sa.String(length=20), nullable=False))
    op.add_column('news', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('news', sa.Column('published_at', sa.DateTime(), nullable=True))
    op.add_column('news', sa.Column('is_fake', sa.Boolean(), nullable=True))
    op.add_column('news', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('news', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('news', 'source',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('news', 'source',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('news', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('news', 'updated_at')
    op.drop_column('news', 'is_fake')
    op.drop_column('news', 'published_at')
    op.drop_column('news', 'country')
    op.drop_column('news', 'language')
    op.drop_column('news', 'url')
    op.drop_column('news', 'author')
    # ### end Alembic commands ###
